name: Azure - Create Resource Group
run-name: ${{ github.actor }} is running workflow Create Resource Group
on:
  workflow_dispatch:
    inputs:
      resourceGroupName:
        description: "Resource Group Name"
        required: true
        type: string

# https://github.com/marketplace/actions/azure-login
jobs:
  jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Azure Context
        uses: azure/powershell@v2
        with:
        azPSVersion: "latest"
        inlineScript: |
          Get-AzContext


