name: Mon premier workflow
on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repository code
      - uses: actions/checkout@v4
      - name: Perform a Pester unit test
        shell: pwsh
        run : |
          Invoke-Pester
