name: Mon premier workflow
on: [push]

jobs:
  pester-tests:
    name: Pester test  
    runs-on: windows-2019
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Perform a Pester unit test
        shell: pwsh
        run : |
          . ".\lib_powershell.ps1"
          Invoke-Pester
