name: Mon premier workflow
on:
  workflow_dispatch:
    inputs:
      message:
        description: "Enter your message"
        required: true
        type: string

jobs:
  job_1:
    name: Job 1
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: display message
        shell: pwsh
        run : |
         write-host "env message : $($env:message)"
         write-host "message : $($message)"
